version: '3.7'

services:
  web:
    build: .
    command: >
      bash -c "python /app/manage.py migrate --noinput
      && python /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
